### ISSUE TITLE
Pour une Europe plus juste, neutralisons les sociétés écrans à commencé la collecte des signatures

### ISSUE THREAD

**Issue by sdm94** [Changaco/citizens-initiatives#11]
l'ICE "Pour une Europe plus juste, neutralisons les sociétés écrans" a commencé à recolter ses signatures aujourd'hui. Le site de l'ICE est http://www.transparencyforall.org/ (et non http://www.transparency.org). La page pour les signatures est : https://ec.europa.eu/citizens-initiative/REQ-ECI-2014-000009/public/index.do

Cordialement

**Comment by Changaco** [comment]
Modifications effectuées.
