### ISSUE TITLE
site de l'ice "STOP PLASTIC IN THE SEA"

### ISSUE THREAD

**Issue by sdm94** [Changaco/citizens-initiatives#13]

**Comment by Changaco** [comment]
Ils n'ont pas l'air d'avoir un site.

**Comment by sdm94** [comment]
désolé j'ai oublié de mettre le lien : http://www.expeditionmed.eu/fr/ on ne sait pas encore s'il feront un site dédié à l'ICE mais c'est bien les organisateurs

**Comment by Changaco** [comment]
Ajouté.
